name: issue-workflow

on:
  issues:  # 'issue' -> 'issues'로 수정
    types: [opened]

jobs:
  issue-job:  # 'jobs' 섹션은 반드시 포함되어야 함
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github action111
     