name: push-workflow
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    -name: step2
     run: l
      echo hello world
      echo github action
    -name: step3
     run: echo hiyo
