name: issue-comment-workflow

on:
  issue_comment:

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a PR comment
        if: ${{ github.event.issue.pull_request != null }}  # Null 값 검사 추가
        run: echo "This is a PR comment: ${{ github.event.issue.pull_request }}"

  issue-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is an issue comment
        if: ${{ github.event.issue.pull_request == null }}  # Null 값 검사
        run: echo "This is an issue comment."